server:
  port: 5000
spring:
  jpa:
    database:
    show-sql: true
    hibernate:
      ddl-auto: none
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      hibernate.id.new_generator_mappings: true
      jdbc:
        lob:
          non-contextual-creation: true
  datasource:
    url: jdbc:postgresql://ec2-3-223-21-106.compute-1.amazonaws.com:5432/d54pg430rlu0i9
    userName: siddjcoyujsyyv
    password: d7c1309231c8e36ee52215f3d2cb9a8dd145f01d2f0ee1fee9f65bd5849e40f4
    driverClassName: org.postgresql.Driver
  liquibase:
    changeLog: classpath:config/liquibase/master.xml
    contexts: pg
assm:
  app:
    jwtSecret: jwtAssmSecretKey
    jwtExpiration: 86400

