server:
  port: ${PORT:5000}
spring:
  profiles:
    active: @activatedProperties@
  jpa:
    database:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    changeLog: classpath:config/liquibase/master.xml
    contexts: pg
assm:
  app:
    jwtSecret: jwtAssmSecretKey
    jwtExpiration: 86400
