server:
    port: ${PORT:5000}
spring:
    profiles:
        active: @activatedProperties@
    jpa:
        database:
        show-sql: true
        hibernate:
            ddl-auto: none
    datasource:
        driverClassName: org.postgresql.Driver
    liquibase:
        changeLog: classpath:config/liquibase/master.xml
        contexts: pg
assm:
    app:
        jwtSecret: jwtAssmSecretKey
        jwtExpiration: 86400
